//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapolnenieDOC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TexnikymBDEntities : DbContext
    {
        public TexnikymBDEntities()
            : base("name=TexnikymBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ШаблонГруппы> ШаблонГруппы { get; set; }
        public virtual DbSet<Студенты2> Студенты2 { get; set; }
        public virtual DbSet<ШаблонСтудентов> ШаблонСтудентов { get; set; }
    }
}
