//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapolnenieDOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты2
    {
        public string ФИО { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public string ПаспортныеДанные { get; set; }
        public string МедицинскийПолис { get; set; }
        public string Снилс { get; set; }
        public string ИНН { get; set; }
        public int id { get; set; }
    }
}
