//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapolnenieDOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ШаблонГруппы
    {
        public string ФИО { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public string МестоРождения { get; set; }
        public string АдресПоРегистрации { get; set; }
        public string Телефон { get; set; }
        public string Паспорт { get; set; }
        public string Email { get; set; }
        public int id { get; set; }
    }
}
